# Generated by Django 5.0 on 2024-02-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.TextField(help_text='The tag', max_length=128)),
            ],
            options={
                'indexes': [models.Index(fields=['tag'], name='tags_tag_tag_2ec7df_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tag',), name='tag_unique'),
        ),
    ]
