# Generated by Django 5.0 on 2024-02-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.TextField(blank=True, default=None, help_text='The group of the tag', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
