# Generated by Django 5.0 on 2024-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_group_tag_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='explanation',
            field=models.TextField(blank=True, default=None, help_text='An explanation for the tag/word', max_length=128, null=True),
        ),
    ]
