# Generated by Django 5.0 on 2024-02-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundtone',
            name='duration_rec',
            field=models.FloatField(blank=True, default=None, help_text='A recommended duration in seconds for this sound', null=True),
        ),
    ]
