# Generated by Django 5.0 on 2024-02-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundgenerator',
            name='audio_device_channels',
            field=models.CharField(blank=True, choices=[('1', 'Mono 1'), ('2', 'Mono 2'), ('3', 'Mono 3'), ('4', 'Mono 4'), ('5', 'Mono 5'), ('6', 'Mono 6'), ('7', 'Mono 7'), ('8', 'Mono 8'), ('9', 'Mono 9'), ('10', 'Mono 10'), ('11', 'Mono 11'), ('12', 'Mono 12'), ('13', 'Mono 13'), ('14', 'Mono 14'), ('15', 'Mono 15'), ('16', 'Mono 16'), ('1,2', 'Stereo 1/2'), ('3,4', 'Stereo 3/4'), ('5,6', 'Stereo 5/6'), ('7,8', 'Stereo 7/8'), ('9,10', 'Stereo 9/10'), ('11,12', 'Stereo 11/12'), ('13,14', 'Stereo 13/4'), ('15,16', 'Stereo 15/16')], default=None, help_text='Audio input channels', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='audio_device_kernelsize',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(64, '64'), (128, '128'), (256, '256'), (512, '512'), (1024, '1024')], default=None, help_text='Audio input kernel size', null=True),
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='audio_device_sample_format',
            field=models.SmallIntegerField(blank=True, choices=[(16, '16 bits'), (24, '24 bits'), (32, '32 bits')], default=None, help_text='Audio input resolution', null=True),
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='description',
            field=models.CharField(default=None, help_text='A short description', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='file_path',
            field=models.FilePathField(default=None, help_text='Optional: the file path for the plugin (requried if this is a plugin)', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='filenames',
            field=models.CharField(blank=True, default=None, help_text='Optional: the list of possible file names for the plugin (comma separated)', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='midi_channel',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10'), (10, '11'), (11, '12'), (12, '13'), (13, '14'), (14, '15'), (15, '16')], default=None, help_text='MIDI channel', null=True),
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='midi_in_port_name',
            field=models.CharField(blank=True, default=None, help_text='MIDI IN port name', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='midi_out_port_name',
            field=models.CharField(blank=True, default=None, help_text='MIDI OUT port name', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='name',
            field=models.CharField(help_text="The name of the sound generator: 'SynthMaster', 'Diva', etc.", max_length=64),
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='parameters',
            field=models.JSONField(blank=True, default=None, help_text='Extra Parameters for this generator', null=True),
        ),
    ]
