# Generated by Django 5.0 on 2024-02-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundgenerator',
            name='audio_device_channels',
            field=models.JSONField(default=list, help_text='Audio input channels', null=True),
        ),
    ]
