# Generated by Django 5.0 on 2024-02-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='soundsource',
            name='generator_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='soundtone',
            name='generator_bank_program_is_unique',
        ),
        migrations.RemoveIndex(
            model_name='soundtone',
            name='sounds_soun_generat_5c29f6_idx',
        ),
        migrations.RenameField(
            model_name='soundtone',
            old_name='generator',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='soundbite',
            name='parameters',
            field=models.JSONField(blank=True, default=None, help_text='Parameters for this specific soundbite (source(if+processor parameters)', null=True),
        ),
        migrations.AlterField(
            model_name='soundsource',
            name='name',
            field=models.CharField(help_text="The name of the sound source: 'SynthMaster', 'Diva', etc.", max_length=64),
        ),
        migrations.AlterField(
            model_name='soundsource',
            name='parameters',
            field=models.JSONField(blank=True, default=None, help_text='Extra Parameters for this source', null=True),
        ),
        migrations.AlterField(
            model_name='soundsource',
            name='type',
            field=models.CharField(choices=[('files', 'Files'), ('recording', 'Recording'), ('voice', 'Voice'), ('instrument', 'Instrument')], default='instrument', help_text='Type of source', max_length=16),
        ),
        migrations.AddIndex(
            model_name='soundtone',
            index=models.Index(fields=['source'], name='sounds_soun_source__1b2c6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='soundsource',
            constraint=models.UniqueConstraint(fields=('name',), name='source_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='soundtone',
            constraint=models.UniqueConstraint(fields=('source', 'midi_bank', 'midi_program'), name='source_bank_program_is_unique'),
        ),
    ]
