# Generated by Django 5.0 on 2024-02-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_alter_soundgenerator_audio_device_channels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundDataSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the sound dataset', max_length=64)),
                ('description', models.CharField(default=None, help_text='A short description', max_length=256, null=True)),
                ('last_modified', models.DateTimeField(default=None, help_text='the date/time the file was modified', null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, help_text='the date/time the file was entered in the database')),
            ],
            options={
                'ordering': ['record_date'],
            },
        ),
        migrations.RemoveField(
            model_name='soundbite',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='soundbite',
            name='source',
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='audio_device_name',
            field=models.CharField(blank=True, default=None, help_text='Audio input device', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='soundgenerator',
            name='type',
            field=models.CharField(choices=[('files', 'Audiofiles'), ('recording', 'Recording'), ('instrument', 'Instrument'), ('artist', 'Artist')], default='instrument', help_text='Type of generator', max_length=16),
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameters', models.JSONField(help_text='Parameters for this specific soundbite (generator(if+processor parameters)')),
                ('file_path', models.FilePathField(help_text='File path of the waveform', max_length=512)),
                ('last_modified', models.DateTimeField(default=None, help_text='the date/time the file was modified', null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, help_text='the date/time the file was entered in the database')),
                ('processor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sounds.soundprocessor')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.soundsource')),
            ],
            options={
                'ordering': ['record_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='sounddataset',
            constraint=models.UniqueConstraint(fields=('name',), name='sounddataset_name_is_unique'),
        ),
        migrations.AddField(
            model_name='sound',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sounddataset'),
        ),
        migrations.DeleteModel(
            name='SoundBite',
        ),
        migrations.AddIndex(
            model_name='sound',
            index=models.Index(fields=['record_date'], name='sounds_soun_record__ff4c26_idx'),
        ),
        migrations.AddIndex(
            model_name='sound',
            index=models.Index(fields=['file_path'], name='sounds_soun_file_pa_904cf1_idx'),
        ),
    ]
