# Generated by Django 5.0 on 2024-02-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_alter_soundgenerator_nature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundsource',
            name='category',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('bass', 'Bass'), ('lead', 'Lead'), ('piano', 'Piano'), ('keyboard', 'Keyboard'), ('string', 'String'), ('ensemble', 'Ensemble'), ('wind', 'Wind'), ('brass', 'Brass'), ('synth', 'Synth'), ('drone', 'Drone'), ('drum', 'Drum'), ('percussion', 'Percussion'), ('guitar', 'Guitar'), ('rythm', 'Rythm'), ('sample', 'Sample'), ('soundfx', 'Sound Fx'), ('voice', 'Voice'), ('baritone', 'Baritone'), ('alto', 'Alto'), ('soprano', 'Soprano')], default='unknown', help_text='Category of sound', max_length=16),
        ),
    ]
