# Generated by Django 5.0 on 2024-02-15 17:45

import sounds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_alter_soundgenerator_audio_device_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundgenerator',
            name='audio_device_channels',
            field=models.JSONField(default=sounds.models.default_channels, help_text='Audio input channels', null=True),
        ),
    ]
