# Generated by Django 5.0 on 2024-02-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_soundsource_midi_vel_preferred_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundsource',
            old_name='midi_vel_preferred',
            new_name='midi_velocity_pref',
        ),
    ]
