# Generated by Django 5.0 on 2024-02-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_alter_soundgenerator_audio_device_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundgenerator',
            name='parameters',
            field=models.JSONField(default=None, help_text='Extra Parameters for this generator', null=True),
        ),
    ]
