# Generated by Django 5.0 on 2024-02-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0004_rename_midi_vel_preferred_soundsource_midi_velocity_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundtone',
            name='category',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('bass', 'Bass'), ('pad', 'Pad'), ('lead', 'Lead'), ('piano', 'Piano'), ('keyboard', 'Keyboard'), ('strings', 'Strings'), ('ensemble', 'Ensemble'), ('woodwind', 'Woodwind'), ('brass', 'Brass'), ('synth', 'Synth'), ('drone', 'Drone'), ('drum', 'Drum'), ('percussion', 'Percussion'), ('pluck', 'Pluck'), ('guitar', 'Guitar'), ('rythm', 'Rythm'), ('loop', 'Loop'), ('sample', 'Sample'), ('song', 'Song'), ('soundfx', 'Sound FX'), ('soundscape', 'Soundscape'), ('vocal', 'Vocal'), ('vocoder', 'Vocoder'), ('voice', 'Voice'), ('baritone', 'Baritone'), ('alto', 'Alto'), ('soprano', 'Soprano'), ('spoken', 'Spoken')], default=None, help_text='Category of sound', max_length=16, null=True),
        ),
    ]
