# Generated by Django 5.0 on 2024-02-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_alter_soundtone_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundsource',
            name='extension',
            field=models.CharField(blank=True, default=None, help_text='Optional: the extension file for the synth, to parse the parameters and auto-generate text. Ex: synths.diva', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='soundtone',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='A short description for the sound texture, focussing on the timbre.', max_length=512, null=True),
        ),
    ]
