# Generated by Django 5.0 on 2024-02-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_remove_soundsource_sounds_soun_type_d5a17c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundsource',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='A short description', max_length=512, null=True),
        ),
    ]
