# Generated by Django 5.0 on 2024-02-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0006_soundsource_extension_alter_soundtone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundtone',
            name='autogen',
            field=models.TextField(blank=True, default=None, help_text='Text automatically generated by the system', max_length=512, null=True),
        ),
    ]
