# Generated by Django 5.0 on 2024-02-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0008_remove_soundtone_autogen_soundtone_descrip_tech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundtone',
            old_name='descrip_tech',
            new_name='description_tech',
        ),
    ]
