# Generated by Django 5.0 on 2024-02-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0009_rename_descrip_tech_soundtone_description_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundtone',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='The name of the sound tone', max_length=128, null=True),
        ),
    ]
