# Generated by Django 5.0 on 2024-02-27 09:50

import sounds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0010_soundtone_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundtone',
            old_name='duration_rec',
            new_name='rec_duration',
        ),
        migrations.AddField(
            model_name='soundtone',
            name='rec_midi_range',
            field=models.PositiveSmallIntegerField(blank=True, choices=sounds.models.choice_midi_range, default=None, help_text='A recommended MIDI range for this sound', null=True),
        ),
    ]
