# Generated by Django 5.0 on 2024-02-28 07:25

import sounds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0011_rename_duration_rec_soundtone_rec_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundbite',
            name='description_tech',
            field=models.TextField(blank=True, default=None, help_text='Technical description automatically generated by the system for this soundbite', max_length=512, null=True, verbose_name='Technical Description'),
        ),
        migrations.AlterField(
            model_name='soundtone',
            name='description_tech',
            field=models.TextField(blank=True, default=None, help_text='Technical description automatically generated by the system', max_length=512, null=True, verbose_name='Technical Description'),
        ),
        migrations.AlterField(
            model_name='soundtone',
            name='rec_duration',
            field=models.FloatField(blank=True, default=None, help_text='A recommended duration in seconds for this sound', null=True, verbose_name='Recommended Duration'),
        ),
        migrations.AlterField(
            model_name='soundtone',
            name='rec_midi_range',
            field=models.PositiveSmallIntegerField(blank=True, choices=sounds.models.choice_midi_range, default=None, help_text='A recommended MIDI range for this sound', null=True, verbose_name='Recommended MIDI Range'),
        ),
    ]
