# Generated by Django 5.0 on 2024-05-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0014_soundsource_preset_extra_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundsource',
            name='preset_extra_delay',
        ),
        migrations.AddField(
            model_name='soundsource',
            name='preset_delay_factor',
            field=models.FloatField(blank=True, default=None, help_text='the delay factor to apply to the preset change', null=True),
        ),
    ]
